apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  labels:
    limit: cpu
spec:
  limits:
    - default:
        cpu: "0.5"
      defaultRequest:
        cpu: "0.1"
      type: Container
