apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  labels:
    disktype: ssd
    runs: kind-worker2
spec:
  containers:
    - name: nginx-affinity
      image: nginx:1.18.0
      resources:
        requests:
          cpu: "0.1"
          memory: "64Mi"
        limits:
          cpu: "0.3"
          memory: "128Mi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
                  - Medium
