apiVersion: v1
kind: Pod
metadata:
  name: pod-noexecute
  labels:
    env: development
spec:
  containers:
    - name: nginx
      image: nginx:1.18.0
      resources:
        requests:
          cpu: "0.1"
          memory: "64Mi"
        limits:
          cpu: "0.3"
          memory: "128Mi"
  tolerations:
    - key: special
      operator: Equal
      value: disk
      effect: NoExecute
      tolerationSeconds: 3600
