apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: marcus
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
    - system:authenticated
  usages:
    - digital signature
    - key encipherment
    - client auth
  request: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0diV0Z5WTNWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQW0zWjVsUGJmQ0pZcUdwNTdPU1N3YzZzcWNRMjVrSURTODdMR2dTRGFKWjR3CnlYdFdMd2ZscnkyYXppZmFXQWNvM21DWko0ZnJTZDB5TWdQcFNLU0tIbzgzMjAzb3dFNHhCZFlVQTFTbXpnekQKWG9VNlJHdTVVL21PdTZVc3R3QXVrSktqUnYySXpkcXJ1elcwZVF6TDI3bVBYdm53ZXZaUi8zYTcrZzM1NlFSVgpIcGJ0NVhqK1FnVmpMaXdxSEtZVXp5YWpCeE5Lb09IQU9WaGhxdVkxcEVHN3hJbVNKSWN2dG5pM3llYS9nSkM2CkxJTlRuUUNiaW42M3VqVk5iYW5OYW9DSGRPell5V0NQN0dSWFlIYlZTaWhNc2xXSVdiZW11TXBQY09XL1Zra1IKQ1lNQ1pYcnYyL1ZlRWFuaFhDUngxMXhWUlcvYWhCYXFOdFowVExuaGt3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSHhyd0d6Wi9GSlk3YWw0dzR3ZmgxZ3JndW9YVlRUL1VMYWdkaWRDeHVyTC81d3h1L2ZtCk92ZG9Hb2tQQUJaVnhVcGNWYnFLMGdkTWt6QVhmZjVKSXovdnJKZlpvb0p5aFY3KzFGV05DRys1akxBeDZzNzYKbnVaYzJGRll2bURQWkFQeUROR2g2T2o4Vlo0RjVIcS9uMTFndVgvS1o4M2FpdjBHbjNlZ0pnUFQzeGNpZEcvYQpiVS94RHNTeEYvUWozQ1c5MmdTbGN3NWx3NlJhSDk1TzlpL01NQWMyQko4ZkxQc3gzM2k0M0E0NWFsRWozUVlhClFuMnB0M0VGdE9aUmFoSm5vdVhxbStaMDVndkkyQVI5SFZwbEJGdlFza3FwRE5rTmVCUkxIb3ZmbnpGL0JOeWkKQVdqZ0hneTVyNzllT0l6L2E4QmRla1cxNzVKeGx0anNuTm89Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo="

  # cat marcus.csr | base64 | tr -d "\n"
