apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data
  accessModes:
    - ReadWriteOnce
