apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    tier: frontend
spec:
  containers:
    - name: webapp-color
      image: kodekloud/webapp-color
      resources:
        requests:
          cpu: "0.1"
          memory: "64Mi"
        limits:
          cpu: "0.2"
          memory: "96Mi"
      envFrom:
        - configMapRef:
            name: webapp-config
      # env:
      #   - name: APP_COLOR
      #     valueFrom:
      #       configMapKeyRef:
      #         key: APP_COLOR
      #         name: webapp-config
      # volumes:
      #   - name: webapp-config-volume
      #     configMap:
      #       name: webapp-config
      ports:
        - containerPort: 8080
          protocol: TCP
